## Shiny report generated by HTSanalyzeR2::report() / reportAll().
##
## The application is assembled from the analysed objects serialized next to it
## in 'results.RData'. The layout uses 'bslib' (Bootstrap 5) and the graphs are
## rendered with 'visNetwork'; no hand-maintained JavaScript bundle is needed.

library(shiny)
library(bslib)
library(DT)
library(colourpicker)
library(HTSanalyzeR2)

## ============================================ Loading results ============================================
## results: list(gsca = gsca, nwa = nwa)
results <- readRDS(file = "./results.RData")
gsca <- results$gsca
nwa <- results$nwa
gscaObjs <- NULL
nwaObjs <- NULL
specificGeneset <- results$specificGeneset
cutoff <- results$cutoff

## ============================================ Preprocessing ==============================================
gscaTS <- !is.null(gsca) && inherits(gsca, "list")
nwaTS <- !is.null(nwa) && inherits(nwa, "list")

gscaSeriesTicks <- NULL
nwaSeriesTicks <- NULL

if (!is.null(gsca)) {
  if (gscaTS) {
    gscaObjs <- gsca
    gscaSeriesTicks <- names(gscaObjs)
    for (name in gscaSeriesTicks) {
      gscaObjs[[name]] <- HTSanalyzeR2:::appendLinks(gscaObjs[[name]])
      gscaObjs[[name]] <- HTSanalyzeR2:::combineResults(gscaObjs[[name]])
    }
    gsca <- gscaObjs[[1]]
  } else {
    gsca <- HTSanalyzeR2:::appendLinks(gsca)
    gsca <- HTSanalyzeR2:::combineResults(gsca)
  }

  availableAnalysis <- HTSanalyzeR2:::availableResults(gsca@result, TRUE)
  availableGeneSets <- HTSanalyzeR2:::availableResults(gsca@summary$results, FALSE)
  specificGenesetItem <- if (!is.null(specificGeneset)) "SpecificGeneset" else NULL
}

if (!is.null(nwa)) {
  if (nwaTS) {
    nwaObjs <- nwa
    nwaSeriesTicks <- names(nwaObjs)
    nwa <- nwaObjs[[1]]
  }
}

## =========================================== Helper functions ============================================
trim_result <- function(result, digits = 3) {
  signif_cols <- c("Observed.score")
  round_cols <- c("HyperGeo.Adj.Pvalue", "GSEA.Adj.Pvalue", "Pvalue",
                  "Adjusted.Pvalue", "Expected.Hits")

  cols <- intersect(colnames(result), round_cols)
  result[cols] <- round(result[cols], digits = 3)
  cols <- intersect(colnames(result), signif_cols)
  result[cols] <- signif(result[cols], digits = 3)

  result
}

colValueRender <- function(minZeroValue) {
  JS(paste("function(data, type, row, meta) { return type === 'display' && Number(data) == 0 ? '<",
           minZeroValue, "' : data }"))
}

create_data_table <- function(gscaObj, analysis, genesets) {
  analysis_to_show <- ifelse(analysis == "Significant in both",
                             "Sig.adj.pvals.in.both", paste0(analysis, ".results"))
  res <- gscaObj@result[[analysis_to_show]][[genesets]]
  res <- trim_result(res, digits = 3)

  gseaDispValue <- ifelse(is.null(gscaObj@para$nPermutations), "0",
                          paste(format((1 / gscaObj@para$nPermutations),
                                       scientific = TRUE, digits = 1), sep = ""))
  jsRenders <- list(GSEA = colValueRender(gseaDispValue),
                    HyperGeo = colValueRender('1e-06'))

  columnDefs <- list(
    list(targets = which(colnames(res) == "HyperGeo.Adj.Pvalue") - 1,
         render = jsRenders[["HyperGeo"]]),
    list(targets = which(colnames(res) == "GSEA.Adj.Pvalue") - 1,
         render = jsRenders[["GSEA"]])
  )
  if (analysis != "Significant in both") {
    columnDefs <- list(list(targets = which(colnames(res) %in% c("Pvalue", "Adjusted.Pvalue")) - 1,
                            render = jsRenders[[analysis]]))
  }

  dt_options <- list(pageLength = 13, dom = 'Bfrtip',
                     buttons = c('copy', 'csv', 'pdf', 'print'),
                     columnDefs = columnDefs)
  jsCallback <- JS("table.page(0).draw(false)")
  dt <- DT::datatable(res, filter = 'top', rownames = FALSE, escape = FALSE,
                      extensions = 'Buttons', options = dt_options, callback = jsCallback)
  if (analysis != "Significant in both") {
    dt <- formatStyle(dt, 'Adjusted.Pvalue', target = "row",
                      fontWeight = styleInterval(gscaObj@para$pValueCutoff,
                                                 c('bold', 'weight')))
  }
  dt
}

## "SpecificGeneset" replaces the selected collections with the user-provided
## gene set list, exactly as the single-object report did before.
mapSelection <- function(input) {
  genesets <- input$genesets_map
  specGeneset <- NULL
  if (!is.null(specificGeneset) && input$genesets_map == "SpecificGeneset") {
    genesets <- names(gsca@listOfGeneSetCollections)
    specGeneset <- specificGeneset
  }
  list(gscs = genesets, specificGeneset = specGeneset)
}

create_enrich_map <- function(gscaObj, seriesObjs, resultName, gscs,
                              specificGeneSet = NULL, styling) {
  HTSanalyzeR2::viewEnrichMap(
    gscaObj,
    resultName = resultName,
    gscs = gscs,
    allSig = TRUE,
    gsNameType = "id",
    specificGeneset = specificGeneSet,
    cutoff = cutoff,
    options = styling,
    seriesObjs = seriesObjs)
}

create_network <- function(nwaObj, seriesObjs, styling) {
  HTSanalyzeR2::viewSubNet(nwaObj,
                           options = styling,
                           seriesObjs = seriesObjs)
}

## ============================================ Settings panel ============================================
## Each graph panel owns its own inputs. Ids are prefixed per panel because
## Shiny requires unique input ids across the whole application.
settingsPanel <- function(prefix) {
  ns <- function(id) paste0(prefix, "_", id)
  accordion(
    accordion_panel(
      "Label",
      radioButtons(ns("labelOption"), "Text",
                   choices = c("ID" = "id", "Term" = "term", "None" = "none"),
                   selected = "id", inline = TRUE),
      sliderInput(ns("labelScale"), "Label scale", min = 0.1, max = 4, value = 1, step = 0.1),
      colourpicker::colourInput(ns("labelColor"), "Label colour", value = "#0FAABB")
    ),
    accordion_panel(
      "Nodes",
      sliderInput(ns("nodeScale"), "Scale", min = 0, max = 10, value = 1, step = 0.1),
      sliderInput(ns("nodeOpacity"), "Opacity", min = 0, max = 1, value = 0.8, step = 0.05),
      sliderInput(ns("nodeBorderWidth"), "Border width", min = 0, max = 10, value = 1, step = 0.1),
      colourpicker::colourInput(ns("nodeBorderColor"), "Border colour", value = "#DB1F51"),
      colourpicker::colourInput(ns("nodeColorNA"), "Colour without phenotype", value = "#EDEDED")
    ),
    accordion_panel(
      "Edges",
      sliderInput(ns("edgeScale"), "Scale", min = 0.5, max = 5, value = 1, step = 0.1),
      colourpicker::colourInput(ns("edgeColor"), "Colour", value = "#0099FF")
    ),
    accordion_panel(
      "Colour scheme",
      colourpicker::colourInput(ns("posColor0"), "Positive (high)", value = "#9E1617"),
      colourpicker::colourInput(ns("posColor1"), "Positive (low)", value = "#FFF3F3"),
      colourpicker::colourInput(ns("negColor0"), "Negative (high)", value = "#006A9C"),
      colourpicker::colourInput(ns("negColor1"), "Negative (low)", value = "#F3F3FF")
    ),
    accordion_panel(
      "Layout",
      sliderInput(ns("layoutGravity"), "Gravity", min = -50, max = 50, value = 10, step = 1),
      checkboxInput(ns("layoutLinLogMode"), "Lin-Log mode", FALSE),
      checkboxInput(ns("layoutStrongGravityMode"), "Strong gravity mode", FALSE),
      checkboxInput(ns("layoutOutboundAttractionDistribution"), "Edge repel", FALSE),
      checkboxInput(ns("layoutAdjustSizes"), "Adjust sizes", FALSE),
      checkboxInput(ns("layoutBarnesHutOptimize"), "Barnes-Hut optimize", FALSE)
    ),
    open = "Label"
  )
}

## The settings inputs of a panel, keyed by their prefixed id.
settingsInputs <- function(prefix) {
  ids <- c("labelOption", "labelScale", "labelColor",
           "nodeScale", "nodeOpacity", "nodeBorderWidth", "nodeBorderColor",
           "nodeColorNA", "edgeScale", "edgeColor",
           "posColor0", "posColor1", "negColor0", "negColor1",
           "layoutGravity", "layoutLinLogMode", "layoutStrongGravityMode",
           "layoutOutboundAttractionDistribution", "layoutAdjustSizes",
           "layoutBarnesHutOptimize")
  paste0(prefix, "_", ids)
}

## Read every rendering input of one panel into the option list understood by
## forceGraph() and updateForceGraph(). Defaults are returned for inputs the
## client has not sent yet, so the first render never sees NULL styling.
graphStyling <- function(input, prefix) {
  get <- function(id, default) {
    value <- input[[paste0(prefix, "_", id)]]
    if (is.null(value)) default else value
  }
  list(
    label = list(text = get("labelOption", "id")),
    node = list(
      scale = get("nodeScale", 1),
      opacity = get("nodeOpacity", 0.8),
      borderWidth = get("nodeBorderWidth", 1),
      borderColor = get("nodeBorderColor", "#DB1F51"),
      naColor = substr(get("nodeColorNA", "#EDEDED"), 1, 7),
      labelScale = get("labelScale", 1),
      labelColor = get("labelColor", "#0FAABB")
    ),
    edge = list(scale = get("edgeScale", 1), color = get("edgeColor", "#0099FF")),
    scheme = list(
      pos = list(range = c(get("posColor0", "#9E1617"), get("posColor1", "#FFF3F3"))),
      neg = list(range = c(get("negColor0", "#006A9C"), get("negColor1", "#F3F3FF")))
    ),
    physics = list(
      gravity = get("layoutGravity", 10),
      linLogMode = get("layoutLinLogMode", FALSE),
      strongGravityMode = get("layoutStrongGravityMode", FALSE),
      outboundAttraction = get("layoutOutboundAttractionDistribution", FALSE),
      adjustSizes = get("layoutAdjustSizes", FALSE),
      barnesHutOptimize = get("layoutBarnesHutOptimize", FALSE)
    )
  )
}

## ============================================ Define ui ==================================================
## The graphs are sized in viewport units so that the card, its floating
## visNetwork controls and the summary boxes below all fit the window; a fixed
## pixel height clipped the container on shorter screens.
graphHeight <- "68vh"

panels <- list()

if (!is.null(gsca)) {
  panels <- c(panels, list(bslib::nav_panel(
    "Enrichment Result",
    bslib::card(
      bslib::card_header("Result table"),
      DTOutput("gsca_output")
    ),
    bslib::layout_column_wrap(
      width = "200px",
      uiOutput("numGenesets"),
      uiOutput("numAboveMinimum"),
      uiOutput("para1"),
      uiOutput("para2"),
      uiOutput("para3"),
      uiOutput("para4"),
      uiOutput("para5")
    ),
    if (gscaTS) selectInput("series_tick_res", "Experiment", gscaSeriesTicks),
    selectInput("analysis_res", "Analysis", availableAnalysis),
    selectInput("genesets_res", "Gene set collection", c(availableGeneSets, "ALL"))
  )))

  panels <- c(panels, list(bslib::nav_panel(
    "Enrichment Map",
    bslib::layout_sidebar(
      fillable = FALSE,
      sidebar = bslib::sidebar(settingsPanel("map")),
      bslib::card(
        bslib::card_header("Enrichment map"),
        HTSanalyzeR2:::forceGraphOutput("map_output", height = graphHeight)
      ),
      if (gscaTS) {
        sliderInput("process_map", "Experiment",
                    min = 1, max = length(gscaSeriesTicks), value = 1, step = 1,
                    animate = animationOptions(interval = 1000))
      },
      selectInput("analysis_map", "Analysis", availableAnalysis[-3]),
      selectInput("genesets_map", "Gene set collection",
                  c(specificGenesetItem, availableGeneSets))
    )
  )))
}

if (!is.null(nwa)) {
  panels <- c(panels, list(bslib::nav_panel(
    "Network Analysis",
    bslib::layout_sidebar(
      fillable = FALSE,
      sidebar = bslib::sidebar(settingsPanel("net")),
      bslib::card(
        bslib::card_header("Enriched subnetwork"),
        HTSanalyzeR2:::forceGraphOutput("network_output", height = graphHeight)
      ),
      if (nwaTS) {
        sliderInput("process_net", "Experiment",
                    min = 1, max = length(nwaSeriesTicks), value = 1, step = 1,
                    animate = animationOptions(interval = 1000))
      },
      bslib::layout_column_wrap(
        width = "200px",
        uiOutput("para6"),
        uiOutput("para7"),
        uiOutput("para8"),
        uiOutput("para8b"),
        uiOutput("para9"),
        uiOutput("para10"),
        uiOutput("para10b")
      )
    )
  )))
}

ui <- do.call(
  bslib::page_navbar,
  c(list(
    title = "HTSanalyzeR2",
    id = "main_tab",
    theme = bslib::bs_theme(version = 5, bootswatch = "flatly"),
    ## The graph cards are not fillable: with 'fillable = TRUE' the card is
    ## sized to the viewport, which clipped the graph container and made
    ## visNetwork's floating controls overlap the summary boxes below.
    fillable = FALSE
  ), panels)
)

## ============================================ Define server ==============================================
summaryBox <- function(title, value) {
  bslib::value_box(title = title, value = value)
}

renderGSCASummary <- function(input, output, gscaObj) {
  numGenesets <- ifelse(input$genesets_res != "ALL",
                        gscaObj@summary$gsc[input$genesets_res, 1],
                        sum(gscaObj@summary$gsc[, 1]))
  numAboveMinimum <- ifelse(input$genesets_res != "ALL",
                            gscaObj@summary$gsc[input$genesets_res, 2],
                            sum(gscaObj@summary$gsc[, 2]))

  output$numGenesets <- renderUI(
    summaryBox(paste("Gene sets in", input$genesets_res), numGenesets))
  output$numAboveMinimum <- renderUI(
    summaryBox("Above the minimum size", numAboveMinimum))

  if (input$analysis_res == "GSEA") {
    para <- gscaObj@summary$para$gsea
    output$para1 <- renderUI(summaryBox("P-value cutoff", para[, "pValueCutoff"]))
    output$para2 <- renderUI(summaryBox("Minimum size", para[, "minGeneSetSize"]))
    output$para3 <- renderUI(summaryBox("Correction", para[, "pAdjustMethod"]))
    output$para4 <- renderUI(summaryBox("Permutations", para[, "nPermutations"]))
    output$para5 <- renderUI(summaryBox("Exponent", para[, "exponent"]))
  } else if (input$analysis_res == "HyperGeo") {
    para <- gscaObj@summary$para$hypergeo
    output$para1 <- renderUI(summaryBox("P-value cutoff", para[, "pValueCutoff"]))
    output$para2 <- renderUI(summaryBox("Minimum size", para[, "minGeneSetSize"]))
    output$para3 <- renderUI(summaryBox("Correction", para[, "pAdjustMethod"]))
    output$para4 <- renderUI(NULL)
    output$para5 <- renderUI(NULL)
  } else {
    for (nm in c("para1", "para2", "para3", "para4", "para5")) {
      output[[nm]] <- renderUI(NULL)
    }
  }
}

renderNWASummary <- function(input, output, nwaObj) {
  output$para6 <- renderUI(summaryBox("Interactome", nwaObj@summary$db[, "name"]))
  output$para7 <- renderUI(summaryBox("Species", nwaObj@summary$db[, "species"]))
  output$para8 <- renderUI(summaryBox("Interactome nodes",
                                      format(nwaObj@summary$db[, "node No"], big.mark = ",")))
  output$para8b <- renderUI(summaryBox("Interactome edges",
                                       format(nwaObj@summary$db[, "edge No"], big.mark = ",")))
  output$para9 <- renderUI(summaryBox("FDR", nwaObj@summary$para[, "FDR"]))
  output$para10 <- renderUI(summaryBox("Subnetwork nodes", nwaObj@summary$result[, "node No"]))
  output$para10b <- renderUI(summaryBox("Subnetwork edges", nwaObj@summary$result[, "edge No"]))
}

server <- function(input, output, session) {
  ## ---- result table -------------------------------------------------------
  if (!is.null(gsca)) {
    observeEvent(
      {
        input$series_tick_res
        input$analysis_res
        input$genesets_res
      },
      {
        obj <- gsca
        if (gscaTS) {
          obj <- gscaObjs[[input$series_tick_res]]
        }
        output$gsca_output <- DT::renderDataTable(
          create_data_table(obj, input$analysis_res, input$genesets_res),
          server = FALSE)
        renderGSCASummary(input, output, obj)
      }
    )

    ## ---- enrichment map ---------------------------------------------------
    mapWidget <- reactiveVal(NULL)

    ## Rebuild only when the structural selection changes. Styling is read
    ## under isolate() so that colour/size tweaks are applied through the proxy
    ## instead of rebuilding (and re-laying out) the graph.
    observe({
      selection <- mapSelection(input)
      resultName <- paste0(input$analysis_map, ".results")
      styling <- isolate(graphStyling(input, "map"))
      mapWidget(create_enrich_map(gsca, gscaObjs, resultName,
                                  selection$gscs, selection$specificGeneset,
                                  styling))
    })
    output$map_output <- HTSanalyzeR2:::renderForceGraph(mapWidget())

    ## style changes update the rendered graph in place
    observe({
      styling <- graphStyling(input, "map")
      widget <- mapWidget()
      req(widget)
      HTSanalyzeR2:::updateForceGraph("map_output", widget, styling)
    })

    if (gscaTS) {
      observeEvent(input$process_map, {
        req(mapWidget())
        HTSanalyzeR2:::updateForceGraph(
          "map_output", mapWidget(),
          graphStyling(input, "map"),
          tick = names(gscaObjs)[input$process_map])
      }, ignoreNULL = TRUE)
    }
  }

  ## ---- subnetwork ---------------------------------------------------------
  if (!is.null(nwa)) {
    networkWidget <- reactiveVal(NULL)

    ## The subnetwork has no structural selectors, so it is built once; styling
    ## changes are applied through the proxy below.
    observe({
      styling <- isolate(graphStyling(input, "net"))
      networkWidget(create_network(nwa, nwaObjs, styling))
      renderNWASummary(input, output, nwa)
    })
    output$network_output <- HTSanalyzeR2:::renderForceGraph(networkWidget())

    observe({
      styling <- graphStyling(input, "net")
      widget <- networkWidget()
      req(widget)
      HTSanalyzeR2:::updateForceGraph("network_output", widget, styling)
    })

    if (nwaTS) {
      observeEvent(input$process_net, {
        req(networkWidget())
        HTSanalyzeR2:::updateForceGraph(
          "network_output", networkWidget(),
          graphStyling(input, "net"),
          tick = names(nwaObjs)[input$process_net])
        renderNWASummary(input, output, nwaObjs[[input$process_net]])
      }, ignoreNULL = TRUE)
    }
  }
}

## ============================================ Run application ============================================
shinyApp(ui, server)
