#' CRISPR data set
#'
#' gRNA sequencing data after transducting the CRISPR system into a human cancer
#' cellline as time goes by. They are further pre-processed by MAGeCK. Details please
#' refer to \href{https://sourceforge.net/p/mageck/wiki/Home/}{MAGeCK.}
#'
#' @aliases d13 d25
#'
"d7"


#' limma result of a gene expression data
#'
#' The differential expressed analysis result between CMS4 colon cancer subtype and
#' non-CMS4 of a gene expression dataset with GEO number-"GSE33113" using R package \emph{limma}.
#'
#'
"GSE33113.limma"


#' An object of class 'GSCA'
#'
#' An object of class 'GSCA' generated by \emph{HTSanalyzeR2}.
#'
#'
"gsca"


#' A list of 'GSCA' object
#'
#' A list of 'GSCA' object generated by time-series analysis using \emph{HTSanalyzeR2}.
#'
#'
"gscaTS"


#' An object of class 'NWA'
#'
#' An object of class 'NWA' generated by \emph{HTSanalyzeR2}.
#'
#'
"nwa"


#' A list of 'NWA' object
#'
#' A list of 'NWA' object generated by time-series analysis using \emph{HTSanalyzeR2}.
#'
#'
"nwaTS"


#' An interactome matrix for \emph{Homo Sapiens}
#'
#' An interactome matrix for \emph{Homo Sapiens}.
#'
#'
"Biogrid_HS_Mat"


#' An object of class 'igraph'
#'
#' An object of class 'igraph' built from the interactome data set for
#' \emph{Homo Sapiens} downloaded from the \emph{BioGRID} database.
#'
"Biogrid_HS_Interactome"


#' An object of class 'cellHTS2'
#'
#' An object of class 'cellHTS2' which has been normalized, configured and annotated.
#'
"xn"
