#' CRISPR data set
#'
#' gRNA sequencing data after transducting the CRISPR system into a human cancer
#' cellline as time goes by. They are further pre-processed by MAGeCK. Details please
#' refer to \href{https://sourceforge.net/p/mageck/wiki/Home/}{MAGeCK}.
#'
#' @aliases d13 d25
#' @references
#' Tzelepis K, Koike-Yusa H, De Braekeleer E, et al. A CRISPR Dropout Screen Identifies
#' Genetic Vulnerabilities and Therapeutic Targets in Acute Myeloid Leukemia. Cell Reports.
#'  2016;17(4):1193-1205. doi:10.1016/j.celrep.2016.09.079.
#' @examples
#' data(d7)
#' data(d13)
#' data(d25)
#'
"d7"


#' limma result of a gene expression data
#'
#' The differential expressed analysis result between CMS4 colon cancer subtype and
#' non-CMS4 of a gene expression dataset with GEO number-"GSE33113" using R package \emph{limma}.
#'
#' @examples
#' data(GSE33113_limma)
#'
"GSE33113_limma"


#' An object of class 'GSCA'
#'
#' An object of class 'GSCA' generated by \emph{HTSanalyzeR2}.
#'
#' @examples
#' data(d7_gsca)
"d7_gsca"


#' A list of 'GSCA' object
#'
#' A list of 'GSCA' object generated by time-series analysis using \emph{HTSanalyzeR2}.
#'
#' @examples
#' data(gscaTS)
"gscaTS"


#' An object of class 'NWA'
#'
#' An object of class 'NWA' generated by \emph{HTSanalyzeR2}.
#' @examples
#' data(d7_nwa)
#'
"d7_nwa"


#' A list of 'NWA' object
#'
#' A list of 'NWA' object generated by time-series analysis using \emph{HTSanalyzeR2}.
#'
#' @examples
#' data(nwaTS)
"nwaTS"


#' An interactome matrix for \emph{Homo Sapiens}
#'
#' An interactome matrix for \emph{Homo Sapiens}.
#'
#' @examples
#' data(Biogrid_HS_Mat)
"Biogrid_HS_Mat"


#' An object of class 'igraph'
#'
#' An object of class 'igraph' built from the interactome data set for
#' \emph{Homo Sapiens} downloaded from the \emph{BioGRID} database.
#'
#' @examples
#' data(Biogrid_HS_Interactome)
"Biogrid_HS_Interactome"


#' An object of class 'cellHTS2'
#'
#' An object of class 'cellHTS2' which has been normalized, configured and annotated.
#' @examples
#' data(xn)
"xn"
