#' CRISPR data set
#'
#' gRNA sequencing data after transducting the CRISPR system into a human cancer
#' cellline as time goes by. They are further pre-processed by MAGeCK. Details please
#' refer to \href{https://sourceforge.net/p/mageck/wiki/Home/}{MAGeCK}.
#'
#' @aliases d13 d25
#' @references
#' Tzelepis K, Koike-Yusa H, De Braekeleer E, et al. A CRISPR Dropout Screen Identifies
#' Genetic Vulnerabilities and Therapeutic Targets in Acute Myeloid Leukemia. Cell Reports.
#'  2016;17(4):1193-1205. doi:10.1016/j.celrep.2016.09.079.
#' @examples
#' data(d7)
#' data(d13)
#' data(d25)
#'
"d7"


#' limma result of a gene expression data
#'
#' The differential expressed analysis result between CMS4 colon cancer subtype and
#' non-CMS4 of a gene expression dataset with GEO number-"GSE33113" using R package \emph{limma}.
#'
#' @examples
#' data(GSE33113_limma)
#'
"GSE33113_limma"


#' An object of class 'GSCA'
#'
#' An object of class 'GSCA' generated by \emph{HTSanalyzeR2}.
#'
#' @examples
#' data(d7_gsca)
"d7_gsca"


#' A list of 'GSCA' object
#'
#' A list of 'GSCA' object generated by time-series analysis using \emph{HTSanalyzeR2}.
#'
#' @examples
#' data(gscaTS)
"gscaTS"


#' An object of class 'NWA'
#'
#' An object of class 'NWA' generated by \emph{HTSanalyzeR2}.
#' @examples
#' data(d7_nwa)
#'
"d7_nwa"


#' A list of 'NWA' object
#'
#' A list of 'NWA' object generated by time-series analysis using \emph{HTSanalyzeR2}.
#'
#' @examples
#' data(nwaTS)
"nwaTS"


#' An interactome matrix for \emph{Homo Sapiens}
#'
#' An interactome matrix for \emph{Homo Sapiens}.
#'
#' @examples
#' data(Biogrid_HS_Mat)
"Biogrid_HS_Mat"


#' An object of class 'igraph'
#'
#' An object of class 'igraph' built from the interactome data set for
#' \emph{Homo Sapiens} downloaded from the \emph{BioGRID} database.
#'
#' @examples
#' data(Biogrid_HS_Interactome)
"Biogrid_HS_Interactome"


#' Example of a normalized, configured and annotated cellHTS object
#'
#' A `cellHTS` object produced by \pkg{cellHTS2}, carrying the measurements, the
#' feature annotation and the sample/control labelling of a small RNAi screen.
#'
#' `cellHTS2` has been removed from Bioconductor. The class of this object comes
#' from that package, so loading `xn` requires it to be installed (for example
#' from a source archive). The statistics that used to be reachable only through
#' such an object are available without it:
#' \code{\link[HTSanalyzeR2]{screenStatTests}} takes the measurements, the
#' annotation and the sample/control labels as plain R objects.
#'
#' @format An object of class \code{cellHTS} with 21888 rows and 2 columns.
#' @seealso \code{\link[HTSanalyzeR2]{screenStatTests}},
#' \code{\link[HTSanalyzeR2]{cellHTS2OutputStatTests}}
#' @examples
#' \dontrun{
#' ## needs cellHTS2, which is no longer part of Bioconductor
#' data(xn)
#' cellHTS2OutputStatTests(xn, annotationColumn = "GeneID", tests = "T-test")
#'
#' ## the same statistics without cellHTS2
#' measurements <- cellHTS2::Data(xn)[, , 1]
#' annotation <- Biobase::fData(xn)$GeneID
#' status <- Biobase::fData(xn)$controlStatus
#' screenStatTests(measurements, annotation, status, tests = "T-test")
#' }
"xn"

#' Expression of a demo data: GSE33113
#'
#' Expression of normalized data GSE33113 in vignette, which contains 21656 genes
#' expression among 78 colon rectal cancer patients.
"GSE33113_exp"

#' Concensus molecular subtype label of GSE33113
#'
#' Concensus molecular subtype label of GSE33113
"GSE33113_label"
