# Generated by using Rcpp::compileAttributes() -> do not edit by hand
# Generator token: 10BE3573-1514-4C36-9D1C-5A225CD40393

calcGScoreCPP <- function(Set, Eso, exponent) {
    .Call('_HTSanalyzeR2_calcGScoreCPP', PACKAGE = 'HTSanalyzeR2', Set, Eso, exponent)
}

